name: Run install.sh on schedule

on:
  schedule:
    - cron: '0 4 * * *'   # Runs every day at 4 AM UTC
  workflow_dispatch:       # Allows manual run from GitHub UI
  push:
    branches:
      - DEV                # Also runs when you push to DEV

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run shell script
        run: |
          chmod +x install.sh
          ./install.sh
